### ISSUE TITLE
UDP Connection 

### ISSUE THREAD

**Issue by erra12** [carrierdown/mutateful#38]
I get the bug "On macOS there seems to sometimes be an issue with activating the externals needed for the patcher to work"
which i can resolve as by opening the m4l device as you suggested.
But as soon as i close it the connection is lost again. So i would need to keep the device open all the time to work with mutateful.

**Comment by carrierdown** [comment]
Ah, that's a bummer. I don't know what causes this issue, but one thing you could try is to clone/download the whole repo and use the mutateful-connector.amxd that's contained in the root of this repo. You could experiment with freezing/unfreezing the device and see if this resolves the issue. Let me know if this helps :)

**Comment by erra12** [comment]
Thanks for your quick response!
It's actually worse, not even naming the clips anymore if i unfreeze.

But even if i let the m4l device open it's just working 1/10 times. Even if there are messages sent as i could see in the terminal window.

I tried downloading the whole repo already but there i cant even open the amxd file. 

Hope there is a solution. Tried the earlier version already without success and was hoping for a solution with a further update. - love the idea!

**Comment by carrierdown** [comment]
What happens when you try to load the amxd-file directly from the repo? 

The only other suggestion I have is to repatch the udpsender and udpreceiver objects in the patcher, because something seems to be off such that it can't find the files it needs to function properly. You could maybe try this with the amxd you're able to open, just duplicate the udp objects and patch them in the same way as the original objects, then delete the original objects once the patching is completed. Save the patcher under a new name, then try this one instead.

**Comment by erra12** [comment]
Ah i think i said it wrong. The UPD objects are found since I downloaded the whole repo. But the formulas still don't work.

**Comment by carrierdown** [comment]
I see. You could take a look at this thread, it's quite long but there are several people resolving their issues with mutateful on Mac towards the end of it, so might give you some ideas for things to try :)

https://github.com/carrierdown/mutateful/issues/14

**Comment by carrierdown** [comment]
Closed due to inactivity
